### ISSUE TITLE
ValueError: Davis root folder must be named "DAVIS"

### ISSUE THREAD

**Issue by kmaninis** [albertomontesg/davis-interactive#31]
This:
ValueError: Davis root folder must be named "DAVIS"

We think this shouldn't be enforced, if the scribbles are not there.
Some people have DAVIS-2016 and DAVIS-2017 named like this, especially the 'veterans' who have worked on the former one!

**Comment by albertomontesg** [comment]
A warning can not be triggered, because if the user only has the annotation and not the scribbles, and its root is called `DAVIS-2017`, the code will download the scribbles for the user and try to decompress the zip (the same happens with the images and annotations zips) on the `DAVIS` folder. A warining does not make sense because, even with the scribbles downloaded, won't be able to find them on the `DAVIS-2017` folder.

**Comment by kmaninis** [comment]
Then better leave it without a warning, and leave it to be the user's responsibility. If they changed the folder name, they should have a good reason for it.

**Comment by kmaninis** [comment]
Hi, since in the end we do not provide any automatic download of dataset, could we give the users the freedom to name DAVIS as they want? Otherwise I will change the documentation to support strict naming to "DAVIS".
